// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID         int64 `json:"id"`
	AcccountID int64 `json:"acccount_id"`
	// can be positive or negative
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID             int64 `json:"id"`
	FromAcccountID int64 `json:"from_acccount_id"`
	ToAcccountID   int64 `json:"to_acccount_id"`
	// can be only positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
